services:
  backend:
    container_name: familytree-backend
    build:
      context: ./family-tree-backend/familytree/familytree
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret

  frontend:
    container_name: familytree-frontend
    build:
      context: ./FamilyTree
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  mysql:
    container_name: guide-mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: